language: cpp

branches:
  only:
   - master

matrix:
  include:
# trusty is needed for Qt5
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
#    - os: osx
#      compiler: clang

script:
- mkdir build && cd build && cmake .. && make && cmake -E tar "cfvz" TestICCPP-$TRAVIS_OS_NAME.tgz TestICCP

before_install:
  -if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update -qq && sudo apt-get install -qq qtbase5-dev;
    else brew update && brew install qt;
    fi
    
after_success:
- echo "after sucess"

#deploy:
#  provider: releases
#  skip_cleanup: true
#  api_key:
#    secure: RFdDwBjvg/91TmcHALdZP71usom9owrCFkZ9bkcF56JU5Urug37AAn/DODezBsfMh1zORpjhlTgM7a+vVGPY2CZXTYTw7IbJa9+dnoKAYL3ArH9ywQpeV2ls+QI8HoWMwpaQp/svb8UIp2aue0pGQBtkSfQd9rRKr5MbXUoJRx2j6/625CFreZ/e6Aip5SQXhnpBZVyPDGHWpp857u1PRHlxlKr1wVklvNU0HFV0FxWJGm0nBejb6mJ4uLyejD0ZO1StIKXC1IxMWXklQnoHH2ln6KnNz1P8dDWv9Dc43eCi9VeudOTcXpALlRG35Lyy4DOkjYvvnVFph5z0lQX0ZaOJI/iH0X7Kn5UyN0WNm02qwBh+fMHKPtLuKyVTuEytMY0Hkyuw/zpz8lWf2hZGVK3xOKqE80+XhcB7nW5m4TNxJTkkxRNit0QNoOFnilgYJ1ZWD35tA0/gjiSe6/N0C7xKYwU/XXoSEA0x47nAaSr6f3TdHyMyaUUCyJ0ypJAoRnznyfu4GdmCqKF2ZKtv67s4OM2hmg9MfY8l/Q69Xe90eJgi8FNgavYw2VFTK0chCLAV/Gegw6hCCyDK7QTjYjJgUTNI9UdDzbXWeQGKLu8jmmEVJAhPkRyQ+cAbjSKwhGAoTnIZJHH3JmqpFdxQufJPEwFG4LTpDmNksLhIsCE=
#  file: TestICCPP-$TRAVIS_OS_NAME.tgz
#  on:
#    repo: gmaillet/testIcCPP
