  
build_script:
  - echo Running cmake...
  - mkdir build
  - cd build
  - set QTDIR=C:\Qt\5.8\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin
  - cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build . --config Release
  - mkdir Release\platforms
  - mkdir Release\imageformats
  - copy %QTDIR%\bin\Qt5Core.dll Release
  - copy %QTDIR%\plugins\imageformats\* Release\imageformats
  - copy %QTDIR%\plugins\platforms\qwindows.dll Release\platforms
  - dir
  
  
after_build:
  - 7z a TestIcCPP.zip Release\*
  
artifacts:
  path: build\TestIcCPP.zip
  name: testIcCPP_win
  
deploy:
  description: 'AppVeyor build'
  artifact: testIcCPP_win
  auth_token:
    secure: LDoltDSff/8u4l/GIIV2LWwtiS2fQATX8kTdJ1Kw7JeTa568+l27lFcpnUfiNgfk
  provider: GitHub
  on:
    appveyor_repo_tag: true
